remote.add_interface("MoreScienceRefresh", {
  milestones_presets = function()
    return {
      ["My MoreScienceRefresh Mod"] = {
        required_mods = { "MoreScienceRefresh" },
        milestones = {
          { type = "group",      name = "Science" },
          { type = "item",       name = "automation-science-pack",                  quantity = 1 },
          { type = "item",       name = "logistic-science-pack",                    quantity = 1 },
          { type = "item",       name = "military-science-pack",                    quantity = 1 },
          { type = "item",       name = "chemical-science-pack",                    quantity = 1 },
          { type = "item",       name = "production-science-pack",                  quantity = 1 },
          { type = "item",       name = "utility-science-pack",                     quantity = 1 },
          { type = "item",       name = "electric-power-science-pack",              quantity = 1 },
          { type = "item",       name = "advanced-automation-science-pack",         quantity = 1 },
          { type = "item",       name = "advanced-logistic-science-pack",           quantity = 1 },
          { type = "item",       name = "rainbow-science-pack",                     quantity = 1 },
          { type = "item",       name = "space-science-pack",                       quantity = 1 },
          { type = "item",       name = "automation-science-pack",                  quantity = 1000,  next = "x10" },
          { type = "item",       name = "logistic-science-pack",                    quantity = 1000,  next = "x10" },
          { type = "item",       name = "military-science-pack",                    quantity = 1000,  next = "x10" },
          { type = "item",       name = "chemical-science-pack",                    quantity = 1000,  next = "x10" },
          { type = "item",       name = "production-science-pack",                  quantity = 1000,  next = "x10" },
          { type = "item",       name = "utility-science-pack",                     quantity = 1000,  next = "x10" },
          { type = "item",       name = "electric-power-science-pack",              quantity = 1000,  next = "x10" },
          { type = "item",       name = "advanced-automation-science-pack",         quantity = 1000,  next = "x10" },
          { type = "item",       name = "advanced-logistic-science-pack",           quantity = 1000,  next = "x10" },
          { type = "item",       name = "rainbow-science-pack",                     quantity = 1000,  next = "x10" },
          { type = "item",       name = "space-science-pack",                       quantity = 10000, next = "x10" },

          { type = "group",      name = "Infused Science" },
          { type = "item",       name = "infused-automation-science-pack",          quantity = 1 },
          { type = "item",       name = "infused-logistic-science-pack",            quantity = 1 },
          { type = "item",       name = "infused-military-science-pack",            quantity = 1 },
          { type = "item",       name = "infused-chemical-science-pack",            quantity = 1 },
          { type = "item",       name = "infused-production-science-pack",          quantity = 1 },
          { type = "item",       name = "infused-utility-science-pack",             quantity = 1 },
          { type = "item",       name = "infused-electric-power-science-pack",      quantity = 1 },
          { type = "item",       name = "infused-advanced-automation-science-pack", quantity = 1 },
          { type = "item",       name = "infused-advanced-logistic-science-pack",   quantity = 1 },
          { type = "item",       name = "infused-space-science-pack",               quantity = 1 },
          { type = "item",       name = "infused-automation-science-pack",          quantity = 1000,  next = "x10" },
          { type = "item",       name = "infused-logistic-science-pack",            quantity = 1000,  next = "x10" },
          { type = "item",       name = "infused-military-science-pack",            quantity = 1000,  next = "x10" },
          { type = "item",       name = "infused-chemical-science-pack",            quantity = 1000,  next = "x10" },
          { type = "item",       name = "infused-production-science-pack",          quantity = 1000,  next = "x10" },
          { type = "item",       name = "infused-utility-science-pack",             quantity = 1000,  next = "x10" },
          { type = "item",       name = "infused-electric-power-science-pack",      quantity = 1000,  next = "x10" },
          { type = "item",       name = "infused-advanced-automation-science-pack", quantity = 1000,  next = "x10" },
          { type = "item",       name = "infused-advanced-logistic-science-pack",   quantity = 1000,  next = "x10" },
          { type = "item",       name = "infused-space-science-pack",               quantity = 10000, next = "x10" },

          { type = "group",      name = "Progress" },
          { type = "item",       name = "locomotive",                               quantity = 1 },
          { type = "item",       name = "purifier",                                 quantity = 1 },
          { type = "item",       name = "lumber-mill",                              quantity = 1 },
          { type = "item",       name = "wood-plantation",                          quantity = 1 },
          { type = "item",       name = "arc-furnace",                              quantity = 1 },
          { type = "item",       name = "chemical-stager",                          quantity = 1 },
          { type = "item",       name = "thermal-plant",                            quantity = 1 },
          { type = "item",       name = "rocket-assembling-machine",                quantity = 1 },
          { type = "fluid",      name = "petroleum-gas",                            quantity = 1 },
          { type = "item",       name = "construction-robot",                       quantity = 1 },

          { type = "technology", name = "rocket-silo",                              quantity = 1 },
          { type = "item",       name = "spidertron",                               quantity = 1 },

          { type = "group",      name = "Power" },
          { type = "item",       name = "solar-panel",                              quantity = 1 },
          { type = "item",       name = "solar-panel",                              quantity = 1000,  next = "x10" },
          { type = "item",       name = "nuclear-reactor",                          quantity = 1 },

          { type = "group",      name = "Kills" },
          { type = "kill",       name = "medium-biter",                             quantity = 1 },
          { type = "kill",       name = "big-biter",                                quantity = 1 },
          { type = "kill",       name = "behemoth-biter",                           quantity = 1 },
          { type = "kill",       name = "behemoth-biter",                           quantity = 1000,  next = "x10" },
          { type = "kill",       name = "character",                                quantity = 1,     next = "x5", hidden = true },
        }
      },
    }
  end
})
